// This file is generated by scripts/generate-webview-bindings.mjs.
// Edit the Rust command contract or the generator, then run bun run bindings:generate.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import { listen, type EventCallback } from "@tauri-apps/api/event";
import type { TranscriptDeliveredEvent } from "../bindings";

export const commands = {
  async cancelOperation(): Promise<void> {
    await TAURI_INVOKE("cancel_operation");
  },
};

export const events = {
  transcriptDeliveredEvent: {
    listen(callback: EventCallback<TranscriptDeliveredEvent>) {
      return listen("transcript-delivered-event", callback);
    },
  },
};
