// This file is generated by scripts/generate-webview-bindings.mjs.
// Edit the Rust command contract or the generator, then run bun run bindings:generate.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import { listen, type EventCallback } from "@tauri-apps/api/event";
import type { OutputTargetLockEvent } from "../bindings";

export const commands = {
  async getAppLanguage(): Promise<string> {
    return await TAURI_INVOKE("get_app_language");
  },
  async getOutputTargetLock(): Promise<OutputTargetLockEvent> {
    return await TAURI_INVOKE("get_output_target_lock");
  },
  async releaseOutputTargetLock(): Promise<void> {
    await TAURI_INVOKE("release_output_target_lock");
  },
};

export const events = {
  outputTargetLockEvent: {
    listen(callback: EventCallback<OutputTargetLockEvent>) {
      return listen("output-target-lock-event", callback);
    },
  },
};
