// This file is generated by scripts/generate-webview-bindings.mjs.
// Edit the Rust command contract or the generator, then run bun run bindings:generate.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import type { PickArmed, PickerGesture, PickerWindow } from "../bindings";

export const commands = {
  async listPickerWindows(): Promise<PickerWindow[]> {
    return await TAURI_INVOKE("list_picker_windows");
  },
  async resolveWindowPick(gesture: PickerGesture): Promise<PickArmed> {
    return await TAURI_INVOKE("resolve_window_pick", { gesture });
  },
};
